review changes
PumpkinSeed/sqlfuzz pull request #20
Opened 2021-03-16 15:37 UTC by srinidhis94

**Changes**
* Adding boolean in postgres.
* Creating postgres example file.
* Support for precision and scale in floating point.

2021-03-16 15:39 UTC, srinidhis94 commented
@PumpkinSeed , @borosr  can you guys check this ? Have added few things missed from previous review and added boolean support which got missed earlier and  float precision support in action.

2021-03-16 15:41 UTC, srinidhis94 commented
CI/CD is broken. Shall I add postgres service and necessary changes or shall I remove postgres test in main_test.go ?

2021-03-16 15:43 UTC, PumpkinSeed requested changes
Amazing, thanks.

2021-03-16 15:43 UTC, PumpkinSeed commented on main_test.go
> +func TestFuzzPostgres(t *testing.T) {
Let me first figure out how I can add postgres to the Github Actions.

2021-03-16 15:43 UTC, PumpkinSeed commented on drivers/postgres_example_test.go
> +const CreateTable = `CREATE TABLE IF NOT EXISTS pg_data_types (
Can you add some of them as NOT NULL, just to handle that case as well in the tests.

2021-03-16 16:29 UTC, PumpkinSeed commented
I added the postgres service.

2021-03-16 18:12 UTC, srinidhis94 commented
There seems to be some problem with connecting to postgres. I don't think username and db are reflected correctly. Need to check this once

2021-03-16 22:13 UTC, borosr commented
Hey, I guess the pipeline is failing because @PumpkinSeed added postgres to the actions, but you have to update your forked repo, to see it there. There is some help for that: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

2021-03-17 11:34 UTC, PumpkinSeed commented
I will try to fix it because I guess it's something from our end. 

@srinidhis94 Let me have a bit of time to figure it out. Otherwise if you enjoy to contribute into the project feel free to contact me so we can have a more direct communication.

2021-03-17 14:28 UTC, srinidhis94 commented
Yea.. would like to contribute in free time. Any place to communicate as of now?

2021-03-18 06:26 UTC, PumpkinSeed approved these changes

2021-03-18 06:27 UTC, merged